// <auto-generated />
using System;
using LeitorNfe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeitorNfe.Migrations
{
    [DbContext(typeof(NotaFiscalContext))]
    [Migration("20240111180954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LeitorNfe.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DestCNPJ")
                        .HasColumnType("REAL");

                    b.Property<double?>("DestCPF")
                        .HasColumnType("REAL");

                    b.Property<string>("DestEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestEndereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EmitCNPJ")
                        .HasColumnType("REAL");

                    b.Property<string>("EmitEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmitEndereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumNota")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumPedidoCompra")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalNotaFiscal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("NotaFiscal");
                });

            modelBuilder.Entity("LeitorNfe.Models.NotaFiscalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodProd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumItem")
                        .HasColumnType("INTEGER");

                    b.Property<double>("QuantidadeComprada")
                        .HasColumnType("REAL");

                    b.Property<double>("ValTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("ValUnit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("NotaFiscalItem");
                });

            modelBuilder.Entity("LeitorNfe.Models.NotaFiscalItem", b =>
                {
                    b.HasOne("LeitorNfe.Models.NotaFiscal", "NotaFiscal")
                        .WithMany("NotaFiscalItems")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("LeitorNfe.Models.NotaFiscal", b =>
                {
                    b.Navigation("NotaFiscalItems");
                });
#pragma warning restore 612, 618
        }
    }
}
